/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as CompanyRouteImport } from './routes/_company'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyScheduleRouteImport } from './routes/_company/schedule'
import { Route as CompanyProfessionalsRouteImport } from './routes/_company/professionals'
import { Route as CompanyDashboardRouteImport } from './routes/_company/dashboard'
import { Route as CompanyContractsRouteImport } from './routes/_company/contracts'
import { Route as CompanyBillingRouteImport } from './routes/_company/billing'
import { Route as AppExecutionIdRouteImport } from './routes/app.execution.$id'
import { Route as ApiPublicCronMonthlyBillingRouteImport } from './routes/api/public/cron/monthly-billing'
import { Route as ApiPublicCronGenerateShiftsRouteImport } from './routes/api/public/cron/generate-shifts'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/_company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyScheduleRoute = CompanyScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyProfessionalsRoute = CompanyProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyContractsRoute = CompanyContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyBillingRoute = CompanyBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => CompanyRoute,
} as any)
const AppExecutionIdRoute = AppExecutionIdRouteImport.update({
  id: '/execution/$id',
  path: '/execution/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCronMonthlyBillingRoute =
  ApiPublicCronMonthlyBillingRouteImport.update({
    id: '/api/public/cron/monthly-billing',
    path: '/api/public/cron/monthly-billing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronGenerateShiftsRoute =
  ApiPublicCronGenerateShiftsRouteImport.update({
    id: '/api/public/cron/generate-shifts',
    path: '/api/public/cron/generate-shifts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/billing': typeof CompanyBillingRoute
  '/contracts': typeof CompanyContractsRoute
  '/dashboard': typeof CompanyDashboardRoute
  '/professionals': typeof CompanyProfessionalsRoute
  '/schedule': typeof CompanyScheduleRoute
  '/app/execution/$id': typeof AppExecutionIdRoute
  '/api/public/cron/generate-shifts': typeof ApiPublicCronGenerateShiftsRoute
  '/api/public/cron/monthly-billing': typeof ApiPublicCronMonthlyBillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/billing': typeof CompanyBillingRoute
  '/contracts': typeof CompanyContractsRoute
  '/dashboard': typeof CompanyDashboardRoute
  '/professionals': typeof CompanyProfessionalsRoute
  '/schedule': typeof CompanyScheduleRoute
  '/app/execution/$id': typeof AppExecutionIdRoute
  '/api/public/cron/generate-shifts': typeof ApiPublicCronGenerateShiftsRoute
  '/api/public/cron/monthly-billing': typeof ApiPublicCronMonthlyBillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_company': typeof CompanyRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_company/billing': typeof CompanyBillingRoute
  '/_company/contracts': typeof CompanyContractsRoute
  '/_company/dashboard': typeof CompanyDashboardRoute
  '/_company/professionals': typeof CompanyProfessionalsRoute
  '/_company/schedule': typeof CompanyScheduleRoute
  '/app/execution/$id': typeof AppExecutionIdRoute
  '/api/public/cron/generate-shifts': typeof ApiPublicCronGenerateShiftsRoute
  '/api/public/cron/monthly-billing': typeof ApiPublicCronMonthlyBillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/billing'
    | '/contracts'
    | '/dashboard'
    | '/professionals'
    | '/schedule'
    | '/app/execution/$id'
    | '/api/public/cron/generate-shifts'
    | '/api/public/cron/monthly-billing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/billing'
    | '/contracts'
    | '/dashboard'
    | '/professionals'
    | '/schedule'
    | '/app/execution/$id'
    | '/api/public/cron/generate-shifts'
    | '/api/public/cron/monthly-billing'
  id:
    | '__root__'
    | '/'
    | '/_company'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_company/billing'
    | '/_company/contracts'
    | '/_company/dashboard'
    | '/_company/professionals'
    | '/_company/schedule'
    | '/app/execution/$id'
    | '/api/public/cron/generate-shifts'
    | '/api/public/cron/monthly-billing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicCronGenerateShiftsRoute: typeof ApiPublicCronGenerateShiftsRoute
  ApiPublicCronMonthlyBillingRoute: typeof ApiPublicCronMonthlyBillingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_company': {
      id: '/_company'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_company/schedule': {
      id: '/_company/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof CompanyScheduleRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/professionals': {
      id: '/_company/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof CompanyProfessionalsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/dashboard': {
      id: '/_company/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/contracts': {
      id: '/_company/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof CompanyContractsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/_company/billing': {
      id: '/_company/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof CompanyBillingRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/app/execution/$id': {
      id: '/app/execution/$id'
      path: '/execution/$id'
      fullPath: '/app/execution/$id'
      preLoaderRoute: typeof AppExecutionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/cron/monthly-billing': {
      id: '/api/public/cron/monthly-billing'
      path: '/api/public/cron/monthly-billing'
      fullPath: '/api/public/cron/monthly-billing'
      preLoaderRoute: typeof ApiPublicCronMonthlyBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/generate-shifts': {
      id: '/api/public/cron/generate-shifts'
      path: '/api/public/cron/generate-shifts'
      fullPath: '/api/public/cron/generate-shifts'
      preLoaderRoute: typeof ApiPublicCronGenerateShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompanyRouteChildren {
  CompanyBillingRoute: typeof CompanyBillingRoute
  CompanyContractsRoute: typeof CompanyContractsRoute
  CompanyDashboardRoute: typeof CompanyDashboardRoute
  CompanyProfessionalsRoute: typeof CompanyProfessionalsRoute
  CompanyScheduleRoute: typeof CompanyScheduleRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyBillingRoute: CompanyBillingRoute,
  CompanyContractsRoute: CompanyContractsRoute,
  CompanyDashboardRoute: CompanyDashboardRoute,
  CompanyProfessionalsRoute: CompanyProfessionalsRoute,
  CompanyScheduleRoute: CompanyScheduleRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface AppRouteChildren {
  AppExecutionIdRoute: typeof AppExecutionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExecutionIdRoute: AppExecutionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicCronGenerateShiftsRoute: ApiPublicCronGenerateShiftsRoute,
  ApiPublicCronMonthlyBillingRoute: ApiPublicCronMonthlyBillingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
